#ifndef BOARDS_H
#define BOARDS_H



block map2[LEVEL_SIZE_Y][LEVEL_SIZE_X] =
	{
		FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR,
		WALL, WALL, WALL, WALL, WALL, WALL, WALL, BRED, WALL, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, DLVR,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, WALL, WALL, WALL, FLOR, WALL, WALL, WALL, WALL, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		TRSH, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, WALL, BYELL, WALL, WALL, WALL, WALL, BBLUE, WALL, WALL,
		FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR,
	};

#endif
