#ifndef BOARDS_H
#define BOARDS_H

block map1[LEVEL_SIZE_Y][LEVEL_SIZE_X] =
	{
		FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR,
		WALL, WALL, CTBD, WALL, CTBD, WALL, WALL, WALL, DLVR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		STOVE, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		STOVE, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, 
		};

block map2[LEVEL_SIZE_Y][LEVEL_SIZE_X] =
	{
		FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR,
		WALL, WALL, CTBD, WALL, WALL, WALL, WALL, CTBD, WALL, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, DLVR,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, FLOR, WALL,
		WALL, WALL, STOVE, WALL, WALL, WALL, WALL, STOVE, WALL, WALL
	};

#endif
